### PR TITLE
Neon syntax: deprecated keywords on/off

### PR DESCRIPTION
**Pull request by dg**
- BC break? yes

Deprecated rarely used on/off in favour of true/false and yes/no

### CODE REVIEW

**Comment by gscpeep** [comment]
👍

**Comment by mabar** [comment]
Why not to be strict and accept only true/false?

**Comment by dg** [comment]
Because `yes/no` is widely used in Nette projects.

**Comment by milo** [comment]
And it is shorter and better "English" and I'm using it too :)

**Pull request merged**
