### PR TITLE
Encoder - some problematic letters like "è"

### PR DESCRIPTION
**Pull request by xsuchy09**
- bug fix
- BC break? no (as I know)

I have troubles with some French texts like `Demande non valide. Paramètres erronés.` - nette:neon encode it just like:
```
Demande non valide. Paramètres erronés.
```

But then there was error to read that files. It was about letter `è` So I changed the rules when quotes should be used - `[\x7F-\xFF]` was added. After that texts are encoded with quotes (`"Demande non valide. Paramètres erronés."`) when these letters are in texts and decoding is successful. Maybe not all that letters have to be encoded with quotes - I just choose it as fast solution.

### CODE REVIEW

**Comment by dg** [comment]
What version are you using and what exactly is the problem about reading?

**Comment by xsuchy09** [comment]
Sorry I investigate it and problem is another one. There is no problem with `è` or any other common character. My client is preparing data in excel and google translator and there is a NBSP (not visible) in that problematic texts. When I copy text `Demande non valide. Paramètres erronés.` into the PhpStorm I see it as:
obrazek

Problematic chars are (after `.` and before word `Paramètres`) - Non Breaking SPace. I tried `str_split` and `ord` on that text and this is the problem (NBSP is here as ASCII codes 194 and 160) - so I think it should be added to the list of chars when quotes should be used (there is no problem with quotes ofc):
```
/var/www/test.php:6:string '.' (length=1)
/var/www/test.php:7:int 46

/var/www/test.php:6:string '�' (length=1)
/var/www/test.php:7:int 194

/var/www/test.php:6:string '�' (length=1)
/var/www/test.php:7:int 160

/var/www/test.php:6:string 'P' (length=1)
/var/www/test.php:7:int 80
```

**Comment by xsuchy09** [comment]
You can try this code as test - for example inside `Decoder.phpt` - see attachment.
[test.txt](https://github.com/nette/neon/files/5005917/test.txt)

**Comment by xsuchy09** [comment]
I added `[\x7F-\xFF]` to the encoder condition (when quotes are or not are needed) in this PR and its a solution for this problem (it is for ASCII codes 127 - 255). This range is not needed whole probably - as investigation above.

**Comment by dg** [comment]
I think this issue was fixed in last commit.

**Comment by xsuchy09** [comment]
Yes, this is fixed by that last commit. Please move last tag or create new one. Thanks a lot, great job.

**Pull request closed without merging**
