### PR TITLE
added support for multilines strings [Closes nette/nette#1375]

### PR DESCRIPTION
**Pull request by dg**
```
foo:
    bar: """
        double
        quotes
    """
```

```
foo:
    bar: '''
        single
        quotes
'''
```

```
foo:
    """
    multi
    key   
    """: 123
```

### CODE REVIEW

**Comment by Majkl578** [comment]
I think the ending EOL should not be present in the output. Much like PHP's NOWDOC/HEREDOC:
```php
var_dump(
<<<FOO
abc
def
FOO
);
```

```
string(7) "abc
def"
```

**Comment by dg** [comment]
I am not clear about it… So time will show. Currently is possible to remove EOL this way:

```
foo:
    bar: "
        double
        quotes"
```

**Comment by chemix** [comment]
```
foo:
	bar: """
		\t\t\double
		\t\t\quotes
	"""
	barx: """
		double tohle je radek 
		 quotes
		 enter 
		dalsi nadpis... 
		 br pomoci texty
	"""
	bary: '''
		tdouble
		quotes
	'''
```

**Comment by dg** [comment]
updated

**Pull request merged**
